apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-local-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/test