apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: http-tcp
    - port: 80
      protocol: UDP
      name: http-udp
      targetPort: http-udp
  selector:
    app: server-python
  sessionAffinity: None
  type: LoadBalancer