apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 8080
    
  selector:
    app: server-python
  sessionAffinity: None
  type: LoadBalancer